// @ts-check
import { defineConfig } from 'astro/config';

export default defineConfig({
  site: 'https://www.szlmagyariskola.ca',
  // Every earlier URL generation → current /hu/-prefixed nested routes:
  // Hungarian originals (website.com era), flat English, and un-prefixed nested.
  redirects: {
    '/': '/hu',
    '/rólunk': '/hu/about',
    '/about': '/hu/about',
    '/segitoink': '/hu/about/volunteers',
    '/volunteers': '/hu/about/volunteers',
    '/about/volunteers': '/hu/about/volunteers',
    '/oktatas': '/hu/education',
    '/education': '/hu/education',
    '/tanaraink': '/hu/education/teachers',
    '/teachers': '/hu/education/teachers',
    '/education/teachers': '/hu/education/teachers',
    '/classrooms': '/hu/education/classrooms',
    '/education/classrooms': '/hu/education/classrooms',
    '/csoportjaink': '/hu/education/groups',
    '/groups': '/hu/education/groups',
    '/education/groups': '/hu/education/groups',
    '/órarend': '/hu/education/schedule',
    '/schedule': '/hu/education/schedule',
    '/education/schedule': '/hu/education/schedule',
    '/tandíj--jelentkezés': '/hu/education/tuition',
    '/tuition': '/hu/education/tuition',
    '/education/tuition': '/hu/education/tuition',
    '/taborok': '/hu/camps',
    '/camps': '/hu/camps',
    '/tabor2019': '/hu/camps/2019',
    '/camp2019': '/hu/camps/2019',
    '/camps/2019': '/hu/camps/2019',
    '/tabor2022': '/hu/camps/2022',
    '/camp2022': '/hu/camps/2022',
    '/camps/2022': '/hu/camps/2022',
    '/hírek': '/hu/news',
    '/news': '/hu/news',
    '/n': '/hu/news/calendar',
    '/calendar': '/hu/news/calendar',
    '/news/calendar': '/hu/news/calendar',
    '/faq': '/hu/contact',
    '/contact': '/hu/contact',
  },
});
